name = input('What is your name? ')
print('Nice to meet you ' + name + ', my name is chatbot.')
age = input('How old are you? ')
print('Wow, ' + age + ' years old! I was born today.' )
feeling = input('How are you feeling? ')
print('Glad to hear you are feeling ' + feeling.lower() + '. That is wonderful to hear!')